version: "3"

services:

  sistemacentrale:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build: sistema_centrale/
    volumes:
      - db_sistemacentrale:/data/.
    command:  python ./sistemacentrale.py
    links:
      - db
    depends_on:
      - db
    #https://stackoverflow.com/questions/52322800/docker-compose-how-to-wait-for-other-service-to-be-ready
    # ports:
    #   - 4001:4001
    #   - 4002:4002
      # - 9392:9392

  sistemamobile:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build: sistema_mobile/
    command: python ./sistemamobile.py
    volumes:
      - db_sistemamobile:/list/.
    depends_on:
      - sistemacentrale
      - stazionediriferimento
      - db

  stazionediriferimento:
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      build: stazione_di_riferimento/
      command: python ./stazioneriferimento.py
      depends_on:
        - sistemacentrale
        - db

  antenna:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build: antenna/
    command: python ./antenna.py
    depends_on:
      - stazionediriferimento
      - sistemamobile
      - db

  cli:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build: sistema_mobile/cli/
    depends_on:
      - sistemamobile
      - db

  db:
      image: postgres:14.1-alpine
      environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
      ports:
          - 5432:5432
      volumes: 
          - db:/var/lib/postgresql/data

volumes:
  db:
    # driver: local
  db_sistemacentrale:
  db_sistemamobile:
